# Generated by Django 6.0.6 on 2026-06-29 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ana', models.CharField(max_length=20, unique=True, verbose_name='Código ANA')),
                ('nome', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('rio', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cota_atencao', models.FloatField()),
                ('cota_alerta', models.FloatField()),
                ('cota_inundacao', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('nivel', models.FloatField()),
                ('vazao', models.FloatField(blank=True, null=True)),
                ('chuva', models.FloatField(blank=True, null=True)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='core.estacao')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
